### PR TITLE
Support thephpleague/commonmark 0.19

### LINKED ISSUE #21: support 0.19
Is it possible to update this extension to support `thephpleague/commonmark`
 0.19? Thanks! :)

### PR DESCRIPTION
**Pull request by yenyasinn**
Resolved #21 - added support of new version thephpleague/commonmark

### CODE REVIEW

**Comment by yenyasinn** [comment]
Test is failed due to issue in https://github.com/thephpleague/commonmark/issues/376

**Comment by imliam** [comment]
That issue seems to have been fixed since the test failed.

**Comment by yenyasinn** [comment]
Yes, it is.
Test is failed now for all versions less 0.19. It is correct because thephpleague/commonmark v. 0.19 has been rewritten. CI settings have to be adjusted not to run tests for versions 0.17, 0.18.

**Comment by yenyasinn** [comment]
Test is failed for thephpleague/commonmark v. 0.19 with php 7.1.
Looks like fix in thephpleague/commonmark#376 doesn't work well in php 7.1. So need to ask fix thephpleague/commonmark#376 or just ignore php 7.1. Support of this version will be finished soon https://www.php.net/supported-versions.php.

**Comment by colinodell** [comment]
@yenyasinn That test failed because it was testing against `league/commonmark` 0.19.0:

image

You'll want to install 0.19.3 instead, since that's when the issue was resolved.

**Comment by egnikitin** [comment]
@colinodell, thank you.

**Comment by egnikitin** [comment]
@hason, please check pull request.

**Comment by glensc** [comment]
also, [1.0.0](https://github.com/thephpleague/commonmark/releases/tag/1.0.0) is released now, compatible with 0.19 api, so add `|^1.0`
and, 0.x versions should be specified with [tilde operator], so the correct line is:

```
        "league/commonmark": "~0.19|^1.0"
```

[tilde operator]: https://getcomposer.org/doc/articles/versions.md

**Comment by glensc** [comment]
> @yenyasinn wants to merge 6 commits into `webuni:master` from `yenyasinn:master`

you should *never* create pull request from `master` branch. any commits you add there are included to PR. see what mess you have created from commits tab: https://github.com/webuni/commonmark-table-extension/pull/23/commits

anyway, i've therefore took this branch, rebased against upstream master and fixed composer dependency. 

create the PR that replaces this PR https://github.com/webuni/commonmark-table-extension/pull/24 as I needed the changes **now**.

**Comment by hason** [comment]
@yenyasinn Thanks! Your work is merged via #24.

**Pull request closed without merging**
